micronaut:
  application:
    name: databaseH2Postgresql
#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/micronaut`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:dbuser}
    password: ${JDBC_PASSWORD:theSecretPassword}
jpa:
  default:
    packages-to-scan:
      - 'database.h2.postgresql'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
goda:
  sameName: "Goda"